use_frameworks!

platform :ios, '9.0'

target 'JosephTestSimpleAlert_Example' do
  pod 'JosephTestSimpleAlert', :path => '../'

  target 'JosephTestSimpleAlert_Tests' do
    inherit! :search_paths

    
  end
end
